# Generated by Django 5.2.7 on 2026-05-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('firstname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('lastname', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_email', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
